version: "3.9"

services:
  backend:
    build: ./backend
    container_name: puerta_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: puerta_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: puerta_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: puerta_orion
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
