"""sincronizar_cambios_modelos

Revision ID: 172b75592622
Revises: 2d477911d249
Create Date: 2025-10-07 21:12:49.081293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '172b75592622'
down_revision = '2d477911d249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Los drop_index han sido removidos porque estos índices son necesarios
    # para las restricciones de claves foráneas en MySQL y se gestionan automáticamente
    
    # Cambiar columna 'sexo' a 'nombre' en la tabla puerta_orion_sexo
    # Verificamos si la columna ya existe para hacer la migración idempotente
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('puerta_orion_sexo')]
    
    # Solo agregar la columna si no existe
    if 'nombre' not in columns:
        with op.batch_alter_table('puerta_orion_sexo', schema=None) as batch_op:
            batch_op.add_column(sa.Column('nombre', sa.String(length=150), nullable=True))
    
    # Migrar datos: convertir valores booleanos/tinyint a texto
    # Si sexo = 1 o True -> "Masculino", si sexo = 0 o False -> "Femenino"
    op.execute("""
        UPDATE puerta_orion_sexo 
        SET nombre = CASE 
            WHEN sexo = 1 THEN 'Masculino'
            WHEN sexo = 0 THEN 'Femenino'
            WHEN sexo = 2 THEN 'Otro'
            ELSE 'No especificado'
        END
        WHERE nombre IS NULL OR nombre = ''
    """)
    
    # Ahora hacemos la columna NOT NULL y eliminamos la columna antigua si existe
    with op.batch_alter_table('puerta_orion_sexo', schema=None) as batch_op:
        batch_op.alter_column('nombre',
                              existing_type=sa.String(length=150),
                              nullable=False)
        if 'sexo' in columns:
            batch_op.drop_column('sexo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Los create_index han sido removidos porque estos índices son necesarios
    # para las restricciones de claves foráneas en MySQL y se gestionan automáticamente
    
    # Revertir el cambio de 'nombre' a 'sexo'
    # Primero agregamos la columna antigua como nullable
    with op.batch_alter_table('puerta_orion_sexo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    
    # Migrar datos de vuelta: convertir texto a booleanos/tinyint
    op.execute("""
        UPDATE puerta_orion_sexo 
        SET sexo = CASE 
            WHEN nombre = 'Masculino' THEN 1
            WHEN nombre = 'Femenino' THEN 0
            ELSE 0
        END
        WHERE sexo IS NULL
    """)
    
    # Ahora hacemos la columna NOT NULL y eliminamos la columna nombre
    with op.batch_alter_table('puerta_orion_sexo', schema=None) as batch_op:
        batch_op.alter_column('sexo',
                              existing_type=mysql.TINYINT(display_width=1),
                              nullable=False)
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
