"""cambiar_documento_telefono_correo_direccion_a_varchar

Revision ID: 2d477911d249
Revises: e2bace7221f1
Create Date: 2025-10-07 18:25:57.725697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d477911d249'
down_revision = 'e2bace7221f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminamos los drop_index porque causan conflictos con las foreign keys
    
    with op.batch_alter_table('puerta_orion_personas', schema=None) as batch_op:
        batch_op.alter_column('documento',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('correo_electronico',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('direccion',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('telefono',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_personas', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('direccion',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('correo_electronico',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('documento',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    
    # No recreamos los índices porque no los eliminamos en upgrade
    # ### end Alembic commands ###
