"""Agregar campo saldo_pendiente a tabla cuota

Revision ID: 32930ce69edb
Revises: 1831d7f1988b
Create Date: 2025-10-12 21:58:54.851826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32930ce69edb'
down_revision = '1831d7f1988b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_cuota', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_pendiente', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_cuota', schema=None) as batch_op:
        batch_op.drop_column('saldo_pendiente')

    # ### end Alembic commands ###
