"""Agregar tabla transaccion_mercadopago

Revision ID: 353e00bfc98f
Revises: a905828499b0
Create Date: 2025-10-15 16:16:10.451774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sys
import os

# Add migrations/versions to path for helper imports
migrations_path = os.path.dirname(os.path.abspath(__file__))
if migrations_path not in sys.path:
    sys.path.insert(0, migrations_path)

from _helpers_transaccion_mp import create_transaccion_mercadopago_table, drop_transaccion_mercadopago_table

# revision identifiers, used by Alembic.
revision = '353e00bfc98f'
down_revision = 'a905828499b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables_map = {t.lower(): t for t in inspector.get_table_names()}

    if 'puerta_orion_transaccion_mercadopago' not in tables_map:
        create_transaccion_mercadopago_table(created_at_nullable=False, updated_at_nullable=False)

    if 'puerta_orion_cuota' in tables_map:
        existing_columns_cuota = {col['name'] for col in inspector.get_columns(tables_map['puerta_orion_cuota'])}
        with op.batch_alter_table(tables_map['puerta_orion_cuota'], schema=None) as batch_op:
            if 'saldo_pendiente' not in existing_columns_cuota:
                batch_op.add_column(sa.Column('saldo_pendiente', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_cuota', schema=None) as batch_op:
        batch_op.drop_column('saldo_pendiente')

    drop_transaccion_mercadopago_table()
    # ### end Alembic commands ###
