"""empty message

Revision ID: 607d95db0456
Revises: abn_mens_add_metodo
Create Date: 2025-10-31 09:15:41.108169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '607d95db0456'
down_revision = 'abn_mens_add_metodo'
branch_labels = None
depends_on = None

# Constants for foreign key references
FK_USUARIO_ID = 'puerta_orion_usuario.id_usuario'
FK_CATEGORIA_ID = 'puerta_orion_categoria.id_categoria'
FK_TIPO_EVENTO_ID = 'puerta_orion_tipo_evento.id_tipo_evento'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # PRIMERO: Crear tabla password_reset_tokens (lo más importante)
    if 'puerta_orion_password_reset_tokens' not in existing_tables:
        op.create_table('puerta_orion_password_reset_tokens',
            sa.Column('id_token', sa.Integer(), nullable=False),
            sa.Column('id_usuario', sa.Integer(), nullable=False),
            sa.Column('token', sa.String(length=100), nullable=False),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['id_usuario'], [FK_USUARIO_ID], ),
            sa.PrimaryKeyConstraint('id_token'),
            sa.UniqueConstraint('token')
        )
    
    # Crear tabla puerta_orion_calendario si no existe
    if 'puerta_orion_calendario' not in existing_tables:
        op.create_table('puerta_orion_calendario',
            sa.Column('id_evento', sa.Integer(), nullable=False),
            sa.Column('id_categoria', sa.Integer(), nullable=False),
            sa.Column('id_tipo_evento', sa.Integer(), nullable=False),
            sa.Column('nombre', sa.String(length=250), nullable=False),
            sa.Column('fecha_evento', sa.Date(), nullable=False),
            sa.Column('hora_inicio', sa.Time(), nullable=False),
            sa.Column('hora_fin', sa.Time(), nullable=False),
            sa.Column('lugar', sa.String(length=200), nullable=False),
            sa.Column('descripcion', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['id_categoria'], [FK_CATEGORIA_ID], ),
            sa.ForeignKeyConstraint(['id_tipo_evento'], [FK_TIPO_EVENTO_ID], ),
            sa.PrimaryKeyConstraint('id_evento')
        )
    
    # Crear tabla puerta_orion_galeria si no existe
    if 'puerta_orion_galeria' not in existing_tables:
        op.create_table('puerta_orion_galeria',
            sa.Column('id_galeria', sa.Integer(), nullable=False),
            sa.Column('titulo', sa.String(length=250), nullable=False),
            sa.Column('url_imagen', sa.String(length=500), nullable=False),
            sa.Column('descripcion', sa.Text(), nullable=True),
            sa.Column('fecha_subida', sa.DateTime(), nullable=False),
            sa.Column('id_tipo_evento', sa.Integer(), nullable=True),
            sa.Column('id_categoria', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['id_categoria'], [FK_CATEGORIA_ID], ),
            sa.ForeignKeyConstraint(['id_tipo_evento'], [FK_TIPO_EVENTO_ID], ),
            sa.PrimaryKeyConstraint('id_galeria')
        )
    
    
    # Eliminar tablas solo si existen
    if 'puerta_orion_evento' in existing_tables:
        op.drop_table('puerta_orion_evento')
    
    # Eliminar la tabla directamente - MySQL eliminará automáticamente índices y claves foráneas
    if 'puerta_orion_historial_roles' in existing_tables:
        op.drop_table('puerta_orion_historial_roles')
    
    with op.batch_alter_table('puerta_orion_abonos_mensualidad', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # Verificar si la columna ya existe antes de agregarla
    if 'puerta_orion_cuota' in existing_tables:
        existing_columns = [col['name'] for col in inspector.get_columns('puerta_orion_cuota')]
        if 'saldo_pendiente' not in existing_columns:
            with op.batch_alter_table('puerta_orion_cuota', schema=None) as batch_op:
                batch_op.add_column(sa.Column('saldo_pendiente', sa.Numeric(precision=10, scale=2), nullable=True))

    # Modificar restricción de clave foránea en mensualidad
    if 'puerta_orion_mensualidad' in existing_tables:
        with op.batch_alter_table('puerta_orion_mensualidad', schema=None) as batch_op:
            # Verificar si la restricción existe antes de eliminarla
            existing_constraints = [fk['name'] for fk in inspector.get_foreign_keys('puerta_orion_mensualidad')]
            if 'fk_mensualidad_persona' in existing_constraints:
                batch_op.drop_constraint('fk_mensualidad_persona', type_='foreignkey')
            batch_op.create_foreign_key(None, 'puerta_orion_personas', ['id_persona'], ['id_persona'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_mensualidad', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_mensualidad_persona', 'puerta_orion_personas', ['id_persona'], ['id_persona'], ondelete='RESTRICT')

    with op.batch_alter_table('puerta_orion_deportista', schema=None) as batch_op:
        batch_op.create_index('ix_deportista_tipo_sanguineo', ['id_tipo_sanguineo'], unique=False)
        batch_op.create_index('ix_deportista_eps', ['id_eps'], unique=False)
        batch_op.create_index('ix_deportista_ciudad', ['id_ciudad_recidencia'], unique=False)

    with op.batch_alter_table('puerta_orion_cuota', schema=None) as batch_op:
        batch_op.drop_column('saldo_pendiente')

    with op.batch_alter_table('puerta_orion_abonos_mensualidad', schema=None) as batch_op:
        batch_op.create_index('ix_abono_mensualidad_mensualidad', ['id_mensualidad'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('informaciondeportiva', schema=None) as batch_op:
        batch_op.create_index('ix_informacion_deportiva_institucion', ['id_institucion_registro'], unique=False)

    op.create_table('puerta_orion_historial_roles',
    sa.Column('id_historial', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_rol', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accion', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('fecha_accion', mysql.DATETIME(), nullable=False),
    sa.Column('realizado_por', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('motivo', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('ip_origen', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['puerta_orion_roles.id_rol'], name='puerta_orion_historial_roles_ibfk_2'),
    sa.ForeignKeyConstraint(['id_usuario'], [FK_USUARIO_ID], name='puerta_orion_historial_roles_ibfk_1'),
    sa.ForeignKeyConstraint(['realizado_por'], [FK_USUARIO_ID], name='puerta_orion_historial_roles_ibfk_3'),
    sa.PrimaryKeyConstraint('id_historial'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('puerta_orion_historial_roles', schema=None) as batch_op:
        batch_op.create_index('idx_historial_roles_usuario_rol', ['id_usuario', 'id_rol'], unique=False)
        batch_op.create_index('idx_historial_roles_usuario', ['id_usuario'], unique=False)
        batch_op.create_index('idx_historial_roles_fecha', ['fecha_accion'], unique=False)

    op.create_table('puerta_orion_evento',
    sa.Column('id_evento', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_categoria', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_tipo_evento', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_sesion', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('fecha_evento', sa.DATE(), nullable=False),
    sa.Column('duracion', mysql.TIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('hora_inicio', mysql.TIME(), nullable=True),
    sa.Column('hora_fin', mysql.TIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['puerta_orion_categoria.id_categoria'], name='puerta_orion_evento_ibfk_1'),
    sa.ForeignKeyConstraint(['id_sesion'], ['puerta_orion_sesiones.id_sesion'], name='puerta_orion_evento_ibfk_2'),
    sa.ForeignKeyConstraint(['id_tipo_evento'], ['puerta_orion_tipo_evento.id_tipo_evento'], name='puerta_orion_evento_ibfk_3'),
    sa.PrimaryKeyConstraint('id_evento'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('puerta_orion_password_reset_tokens')
    op.drop_table('puerta_orion_galeria')
    op.drop_table('puerta_orion_calendario')
    # ### end Alembic commands ###
