"""modificar_tabla_eventos_agregar_lugar_descripcion_horas

Revision ID: 72e395f8ae95
Revises: 9c65a75d07c3
Create Date: 2025-10-18 20:36:00.036851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72e395f8ae95'
down_revision = '9c65a75d07c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_inicio', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('hora_fin', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('lugar', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.drop_column('duracion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duracion', mysql.TIME(), nullable=False))
        batch_op.drop_column('descripcion')
        batch_op.drop_column('lugar')
        batch_op.drop_column('hora_fin')
        batch_op.drop_column('hora_inicio')

    # ### end Alembic commands ###
