"""agregar_relaciones_faltantes

Revision ID: 88f1a9167ed6
Revises: 006_marcar_estado_correcto
Create Date: 2025-10-03 10:49:41.011226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f1a9167ed6'
down_revision = '006_marcar_estado_correcto'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Solo agregar las relaciones faltantes, no eliminar índices existentes
    
    with op.batch_alter_table('puerta_orion_personas', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'puerta_orion_sexo', ['id_sexo'], ['id_sexo'])
        batch_op.create_foreign_key(None, 'puerta_orion_tipo_documento', ['id_tipo_documento'], ['id_documento'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_personas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
