"""Correccion de un campo el cual tenia un nombre mal asignado

Revision ID: 932e56d21ca8
Revises: ae5dc1944dd5
Create Date: 2025-10-03 12:37:56.440838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '932e56d21ca8'
down_revision = 'ae5dc1944dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostico_deportista', schema=None) as batch_op:
        batch_op.alter_column('id_diagnostico',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_deportista',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # No eliminar el índice ix_informacion_deportiva_institucion porque está siendo usado por una clave foránea
    # with op.batch_alter_table('informaciondeportiva', schema=None) as batch_op:
    #     batch_op.drop_index('ix_informacion_deportiva_institucion')

    with op.batch_alter_table('puerta_orion_deportista', schema=None) as batch_op:
        # La columna id_diagnostico_deportista ya existe, no es necesario agregarla
        # batch_op.add_column(sa.Column('id_diagnostico_deportista', sa.Integer(), nullable=True))
        
        # No eliminar índices que están siendo usados por claves foráneas
        # batch_op.drop_index('ix_deportista_ciudad')
        # batch_op.drop_index('ix_deportista_eps')
        # batch_op.drop_index('ix_deportista_tipo_sanguineo')
        
        # Eliminar la clave foránea antigua y crear la nueva
        batch_op.drop_constraint('fk_deportista_diagnostico', type_='foreignkey')
        batch_op.create_foreign_key('fk_deportista_diagnostico_nuevo', 'diagnostico', ['id_diagnostico_deportista'], ['id_diagnostico'])
        batch_op.drop_column('id_diagnosco_deportista')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_deportista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_diagnosco_deportista', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_deportista_diagnostico_nuevo', type_='foreignkey')
        batch_op.create_foreign_key('fk_deportista_diagnostico', 'diagnostico', ['id_diagnosco_deportista'], ['id_diagnostico'])
        # Los índices no se eliminaron, por lo que no es necesario recrearlos
        # batch_op.create_index('ix_deportista_tipo_sanguineo', ['id_tipo_sanguineo'], unique=False)
        # batch_op.create_index('ix_deportista_eps', ['id_eps'], unique=False)
        # batch_op.create_index('ix_deportista_ciudad', ['id_ciudad_recidencia'], unique=False)
        batch_op.drop_column('id_diagnostico_deportista')

    # El índice ix_informacion_deportiva_institucion no se elimina, por lo que no es necesario recrearlo
    # with op.batch_alter_table('informaciondeportiva', schema=None) as batch_op:
    #     batch_op.create_index('ix_informacion_deportiva_institucion', ['id_institucion_registro'], unique=False)

    with op.batch_alter_table('diagnostico_deportista', schema=None) as batch_op:
        batch_op.alter_column('id_deportista',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_diagnostico',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
