"""Cambiar tipo de telefono de Integer a String

Revision ID: 9c65a75d07c3
Revises: 32930ce69edb
Create Date: 2025-10-15 15:11:01.978592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c65a75d07c3'
down_revision = '32930ce69edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_personas', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_personas', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=15),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
