"""actualizar_modelo_diagnostico

Revision ID: ae5dc1944dd5
Revises: 88f1a9167ed6
Create Date: 2025-10-03 12:29:37.283259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae5dc1944dd5'
down_revision = '88f1a9167ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Actualizar tabla diagnostico_deportista con nueva estructura
    with op.batch_alter_table('diagnostico_deportista', schema=None) as batch_op:
        # Agregar nuevas columnas
        batch_op.add_column(sa.Column('id_diagnostico', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_deportista', sa.Integer(), nullable=True))
        
        # Crear nuevas claves foráneas
        batch_op.create_foreign_key('fk_diagnostico_deportista_diagnostico', 'diagnostico', ['id_diagnostico'], ['id_diagnostico'])
        batch_op.create_foreign_key('fk_diagnostico_deportista_deportista', 'puerta_orion_deportista', ['id_deportista'], ['id_deportista'])
        
        # Eliminar restricción anterior y columna antigua
        batch_op.drop_constraint('diagnostico_deportista_ibfk_1', type_='foreignkey')
        batch_op.drop_column('diagnostico')
        
        # Hacer las columnas NOT NULL después de migrar los datos
        batch_op.alter_column('id_diagnostico', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('id_deportista', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revertir cambios en diagnostico_deportista
    with op.batch_alter_table('diagnostico_deportista', schema=None) as batch_op:
        # Agregar columna antigua
        batch_op.add_column(sa.Column('diagnostico', mysql.INTEGER(), autoincrement=False, nullable=False))
        
        # Eliminar nuevas claves foráneas
        batch_op.drop_constraint('fk_diagnostico_deportista_diagnostico', type_='foreignkey')
        batch_op.drop_constraint('fk_diagnostico_deportista_deportista', type_='foreignkey')
        
        # Recrear clave foránea anterior
        batch_op.create_foreign_key('diagnostico_deportista_ibfk_1', 'diagnostico', ['diagnostico'], ['id_diagnostico'])
        
        # Eliminar nuevas columnas
        batch_op.drop_column('id_deportista')
        batch_op.drop_column('id_diagnostico')

    # ### end Alembic commands ###
