"""actualizar_modelo_diagnostico

Revision ID: ae5dc1944dd5
Revises: 88f1a9167ed6
Create Date: 2025-10-03 12:29:37.283259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae5dc1944dd5'
down_revision = '88f1a9167ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables_map = {t.lower(): t for t in inspector.get_table_names()}
    if 'diagnostico_deportista' not in tables_map:
        return

    diag_dep_table = tables_map['diagnostico_deportista']
    existing_columns = {col['name'] for col in inspector.get_columns(diag_dep_table)}
    existing_fks = {fk.get('name') for fk in inspector.get_foreign_keys(diag_dep_table)}

    with op.batch_alter_table(diag_dep_table, schema=None) as batch_op:
        if 'id_diagnostico' not in existing_columns:
            batch_op.add_column(sa.Column('id_diagnostico', sa.Integer(), nullable=True))
        if 'id_deportista' not in existing_columns:
            batch_op.add_column(sa.Column('id_deportista', sa.Integer(), nullable=True))

        if 'fk_diagnostico_deportista_diagnostico' not in existing_fks:
            batch_op.create_foreign_key('fk_diagnostico_deportista_diagnostico', 'diagnostico', ['id_diagnostico'], ['id_diagnostico'])
        if 'fk_diagnostico_deportista_deportista' not in existing_fks:
            batch_op.create_foreign_key('fk_diagnostico_deportista_deportista', 'puerta_orion_deportista', ['id_deportista'], ['id_deportista'])

        if 'diagnostico_deportista_ibfk_1' in existing_fks:
            batch_op.drop_constraint('diagnostico_deportista_ibfk_1', type_='foreignkey')
        if 'diagnostico' in existing_columns:
            batch_op.drop_column('diagnostico')

        if 'id_diagnostico' in existing_columns:
            batch_op.alter_column('id_diagnostico', existing_type=sa.Integer(), nullable=False)
        if 'id_deportista' in existing_columns:
            batch_op.alter_column('id_deportista', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revertir cambios en diagnostico_deportista
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables_map = {t.lower(): t for t in inspector.get_table_names()}
    if 'diagnostico_deportista' not in tables_map:
        return

    diag_dep_table = tables_map['diagnostico_deportista']
    existing_columns = {col['name'] for col in inspector.get_columns(diag_dep_table)}

    with op.batch_alter_table(diag_dep_table, schema=None) as batch_op:
        # Agregar columna antigua
        if 'diagnostico' not in existing_columns:
            batch_op.add_column(sa.Column('diagnostico', mysql.INTEGER(), autoincrement=False, nullable=False))
        
        # Eliminar nuevas claves foráneas
        try:
            batch_op.drop_constraint('fk_diagnostico_deportista_diagnostico', type_='foreignkey')
        except Exception:
            pass
        try:
            batch_op.drop_constraint('fk_diagnostico_deportista_deportista', type_='foreignkey')
        except Exception:
            pass
        
        # Recrear clave foránea anterior
        batch_op.create_foreign_key('diagnostico_deportista_ibfk_1', 'diagnostico', ['diagnostico'], ['id_diagnostico'])
        
        # Eliminar nuevas columnas
        if 'id_deportista' in existing_columns:
            batch_op.drop_column('id_deportista')
        if 'id_diagnostico' in existing_columns:
            batch_op.drop_column('id_diagnostico')

    # ### end Alembic commands ###
