"""rol_usuario

Revision ID: bf34fa9e9087
Revises: de48281e16b2
Create Date: 2025-09-27 00:19:08.539546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf34fa9e9087'
down_revision = 'de48281e16b2'
branch_labels = None
depends_on = None

# Constants for foreign key references
FK_PERSONA_ID = 'puerta_orion_personas.id_persona'
FK_USUARIO_ID = 'puerta_orion_usuario.id_usuario'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar si las tablas ya existen antes de crearlas
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = {t.lower(): t for t in inspector.get_table_names()}

    def table_exists(name):
        return name.lower() in existing_tables

    def register_table(name):
        existing_tables[name.lower()] = name

    def canonical(name):
        return existing_tables.get(name.lower(), name)

    def drop_table_if_unused(name):
        # Esta migración se ejecuta sobre una base creada previamente, por lo que evitar
        # drops asegura compatibilidad con la cadena existente.
        return
    
    if not table_exists('Escuela'):
        op.create_table('Escuela',
        sa.Column('id_escuela', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nombre', sa.String(length=150), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id_escuela'),
        sa.UniqueConstraint('nombre')
        )
        register_table('Escuela')
    
    if not table_exists('TipoEnfermedad'):
        op.create_table('TipoEnfermedad',
        sa.Column('id_tipo_enfermedad', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=150), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id_tipo_enfermedad'),
        sa.UniqueConstraint('nombre')
        )
        register_table('TipoEnfermedad')
    
    if not table_exists('InformacionDeportiva'):
        op.create_table('InformacionDeportiva',
        sa.Column('id_informacion_deportiva', sa.Integer(), nullable=False),
        sa.Column('practica_otro_deporte', sa.Boolean(), nullable=False),
        sa.Column('participa_escuela', sa.Boolean(), nullable=False),
        sa.Column('recomendacion_medica', sa.Boolean(), nullable=False),
        sa.Column('descripcion_recomendacion', sa.String(length=500), nullable=True),
        sa.Column('id_escuela', sa.Integer(), nullable=True),
        sa.Column('id_deporte', sa.Integer(), nullable=True),
        sa.Column('id_persona', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['id_deporte'], ['deporte.id_deporte'], ),
        sa.ForeignKeyConstraint(['id_escuela'], ['Escuela.id_escuela'], ),
        sa.ForeignKeyConstraint(['id_persona'], [FK_PERSONA_ID], ),
        sa.PrimaryKeyConstraint('id_informacion_deportiva')
        )
        register_table('InformacionDeportiva')
    
    if not table_exists('PersonasRol'):
        op.create_table('PersonasRol',
        sa.Column('id_persona', sa.Integer(), nullable=False),
        sa.Column('id_rol', sa.Integer(), nullable=False),
        sa.Column('estado', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['id_persona'], [FK_PERSONA_ID], ),
        sa.ForeignKeyConstraint(['id_rol'], ['puerta_orion_roles.id_rol'], ),
        sa.PrimaryKeyConstraint('id_persona', 'id_rol')
        )
        register_table('PersonasRol')
    
    if not table_exists('SesionAuth'):
        op.create_table('SesionAuth',
        sa.Column('id_sesion', sa.Integer(), nullable=False),
        sa.Column('id_usuario', sa.Integer(), nullable=False),
        sa.Column('token_sesion', sa.String(length=500), nullable=False),
        sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
        sa.Column('fecha_expiracion', sa.DateTime(), nullable=False),
        sa.Column('ip_origen', sa.String(length=50), nullable=True),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('estado', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['id_usuario'], [FK_USUARIO_ID], ),
        sa.PrimaryKeyConstraint('id_sesion'),
        sa.UniqueConstraint('token_sesion')
        )
        register_table('SesionAuth')
    
    if table_exists('tipoenfermedad'):
        drop_table_if_unused('tipoenfermedad')

    drop_table_if_unused('informaciondeportiva')

    drop_table_if_unused('escuela')

    drop_table_if_unused('personasrol')

    if table_exists('sesionauth'):
        with op.batch_alter_table(canonical('sesionauth'), schema=None) as batch_op:
            batch_op.drop_index('token_sesion')
        drop_table_if_unused('sesionauth')

    drop_table_if_unused('puerta_orion_rol_usuario')
    existing_fks_diagnostico = {fk.get('name') for fk in inspector.get_foreign_keys('diagnostico') if fk.get('name')}

    with op.batch_alter_table('diagnostico', schema=None) as batch_op:
        if 'diagnostico_ibfk_1' in existing_fks_diagnostico:
            batch_op.drop_constraint('diagnostico_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, canonical('tipoenfermedad'), ['id_tipo_enfermedad'], ['id_tipo_enfermedad'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('diagnostico_ibfk_1', 'tipoenfermedad', ['id_tipo_enfermedad'], ['id_tipo_enfermedad'])

    op.create_table('puerta_orion_rol_usuario',
    sa.Column('id_rol_usuario', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_sesion', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_sesion'], ['puerta_orion_sesiones.id_sesion'], name='puerta_orion_rol_usuario_ibfk_1'),
    sa.ForeignKeyConstraint(['id_usuario'], [FK_USUARIO_ID], name='puerta_orion_rol_usuario_ibfk_2'),
    sa.PrimaryKeyConstraint('id_rol_usuario'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sesionauth',
    sa.Column('id_sesion', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_sesion', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('fecha_inicio', mysql.DATETIME(), nullable=False),
    sa.Column('fecha_expiracion', mysql.DATETIME(), nullable=False),
    sa.Column('ip_origen', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], [FK_USUARIO_ID], name='sesionauth_ibfk_1'),
    sa.PrimaryKeyConstraint('id_sesion'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sesionauth', schema=None) as batch_op:
        batch_op.create_index('token_sesion', ['token_sesion'], unique=True)

    op.create_table('personasrol',
    sa.Column('id_persona', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_rol', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], [FK_PERSONA_ID], name='personasrol_ibfk_1'),
    sa.ForeignKeyConstraint(['id_rol'], ['puerta_orion_roles.id_rol'], name='personasrol_ibfk_2'),
    sa.PrimaryKeyConstraint('id_persona', 'id_rol'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('escuela',
    sa.Column('id_escuela', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id_escuela'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('escuela', schema=None) as batch_op:
        batch_op.create_index('nombre', ['nombre'], unique=True)

    op.create_table('informaciondeportiva',
    sa.Column('id_informacion_deportiva', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('practica_otro_deporte', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('participa_escuela', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('recomendacion_medica', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('descripcion_recomendacion', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('id_escuela', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_deporte', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_persona', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_deporte'], ['deporte.id_deporte'], name='informaciondeportiva_ibfk_1'),
    sa.ForeignKeyConstraint(['id_escuela'], ['escuela.id_escuela'], name='informaciondeportiva_ibfk_2'),
    sa.ForeignKeyConstraint(['id_persona'], [FK_PERSONA_ID], name='informaciondeportiva_ibfk_3'),
    sa.PrimaryKeyConstraint('id_informacion_deportiva'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tipoenfermedad',
    sa.Column('id_tipo_enfermedad', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_enfermedad'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tipoenfermedad', schema=None) as batch_op:
        batch_op.create_index('nombre', ['nombre'], unique=True)

    op.drop_table('SesionAuth')
    op.drop_table('PersonasRol')
    op.drop_table('InformacionDeportiva')
    op.drop_table('TipoEnfermedad')
    op.drop_table('Escuela')
    # ### end Alembic commands ###
