"""Crear todas las tablas del sistema Puerta Orion

Revision ID: de48281e16b2
Revises: 
Create Date: 2025-09-27 00:13:03.130907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de48281e16b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Escuela',
    sa.Column('id_escuela', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_escuela'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('TipoEnfermedad',
    sa.Column('id_tipo_enfermedad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_enfermedad'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('deporte',
    sa.Column('id_deporte', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_deporte'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('puerta_orion_categoria',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('codigo_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=150), nullable=False),
    sa.Column('edad_minima', sa.Integer(), nullable=False),
    sa.Column('edad_maxima', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('codigo_categoria')
    )
    op.create_table('puerta_orion_ciudad_residencia',
    sa.Column('id_ciudad', sa.Integer(), nullable=False),
    sa.Column('nombre_ciudad', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_ciudad'),
    sa.UniqueConstraint('nombre_ciudad')
    )
    op.create_table('puerta_orion_eps',
    sa.Column('id_eps', sa.Integer(), nullable=False),
    sa.Column('nombre_eps', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('codigo_eps', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_eps'),
    sa.UniqueConstraint('nombre_eps')
    )
    op.create_table('puerta_orion_grupo_sanguineo',
    sa.Column('id_tipo_sangre', sa.Integer(), nullable=False),
    sa.Column('tipo_sangre', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_sangre'),
    sa.UniqueConstraint('tipo_sangre')
    )
    op.create_table('puerta_orion_institucion_registro',
    sa.Column('id_institucion', sa.Integer(), nullable=False),
    sa.Column('nombre_institucion', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_institucion'),
    sa.UniqueConstraint('nombre_institucion')
    )
    op.create_table('puerta_orion_metodo_pago',
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.Column('nombre_metodo', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_metodo_pago'),
    sa.UniqueConstraint('nombre_metodo')
    )
    op.create_table('puerta_orion_parentesco',
    sa.Column('id_parentesco', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_parentesco'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('puerta_orion_permisos',
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_permiso'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('puerta_orion_roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_table('puerta_orion_sesiones',
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    op.create_table('puerta_orion_sexo',
    sa.Column('id_sexo', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_sexo')
    )
    op.create_table('puerta_orion_tipo_documento',
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('nombre_documento', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_documento'),
    sa.UniqueConstraint('nombre_documento')
    )
    op.create_table('puerta_orion_tipo_evento',
    sa.Column('id_tipo_evento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_evento')
    )
    op.create_table('diagnostico',
    sa.Column('id_diagnostico', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('id_tipo_enfermedad', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_enfermedad'], ['TipoEnfermedad.id_tipo_enfermedad'], ),
    sa.PrimaryKeyConstraint('id_diagnostico')
    )
    op.create_table('puerta_orion_evento',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_tipo_evento', sa.Integer(), nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('fecha_evento', sa.Date(), nullable=False),
    sa.Column('duracion', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['puerta_orion_categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_sesion'], ['puerta_orion_sesiones.id_sesion'], ),
    sa.ForeignKeyConstraint(['id_tipo_evento'], ['puerta_orion_tipo_evento.id_tipo_evento'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_table('puerta_orion_mensualidad',
    sa.Column('id_mensualidad', sa.Integer(), nullable=False),
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('monto_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['puerta_orion_categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['puerta_orion_metodo_pago.id_metodo_pago'], ),
    sa.PrimaryKeyConstraint('id_mensualidad')
    )
    op.create_table('puerta_orion_rol_permiso',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['puerta_orion_permisos.id_permiso'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['puerta_orion_roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_rol', 'id_permiso')
    )
    op.create_table('puerta_orion_personas',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=50), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=50), nullable=True),
    sa.Column('primer_apellido', sa.String(length=50), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=50), nullable=True),
    sa.Column('documento', sa.Integer(), nullable=False),
    sa.Column('correo_electronico', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('id_mensualidad', sa.Integer(), nullable=True),
    sa.Column('id_sexo', sa.Integer(), nullable=False),
    sa.Column('id_ciudad', sa.Integer(), nullable=False),
    sa.Column('id_tipo_documento', sa.Integer(), nullable=False),
    sa.Column('id_eps', sa.Integer(), nullable=False),
    sa.Column('id_institucion', sa.Integer(), nullable=False),
    sa.Column('id_tipo_sangre', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_ciudad'], ['puerta_orion_ciudad_residencia.id_ciudad'], ),
    sa.ForeignKeyConstraint(['id_eps'], ['puerta_orion_eps.id_eps'], ),
    sa.ForeignKeyConstraint(['id_institucion'], ['puerta_orion_institucion_registro.id_institucion'], ),
    sa.ForeignKeyConstraint(['id_mensualidad'], ['puerta_orion_mensualidad.id_mensualidad'], ),
    sa.ForeignKeyConstraint(['id_sexo'], ['puerta_orion_sexo.id_sexo'], ),
    sa.ForeignKeyConstraint(['id_tipo_documento'], ['puerta_orion_tipo_documento.id_documento'], ),
    sa.ForeignKeyConstraint(['id_tipo_sangre'], ['puerta_orion_grupo_sanguineo.id_tipo_sangre'], ),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('InformacionDeportiva',
    sa.Column('id_informacion_deportiva', sa.Integer(), nullable=False),
    sa.Column('practica_otro_deporte', sa.Boolean(), nullable=False),
    sa.Column('participa_escuela', sa.Boolean(), nullable=False),
    sa.Column('recomendacion_medica', sa.Boolean(), nullable=False),
    sa.Column('descripcion_recomendacion', sa.String(length=500), nullable=True),
    sa.Column('id_escuela', sa.Integer(), nullable=True),
    sa.Column('id_deporte', sa.Integer(), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_deporte'], ['deporte.id_deporte'], ),
    sa.ForeignKeyConstraint(['id_escuela'], ['Escuela.id_escuela'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['puerta_orion_personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id_informacion_deportiva')
    )
    op.create_table('PersonasRol',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['puerta_orion_personas.id_persona'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['puerta_orion_roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_persona', 'id_rol')
    )
    op.create_table('diagnostico_persona',
    sa.Column('id_diagnostico_persona', sa.Integer(), nullable=False),
    sa.Column('diagnostico', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diagnostico'], ['diagnostico.id_diagnostico'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['puerta_orion_personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id_diagnostico_persona')
    )
    op.create_table('puerta_orion_acudiente',
    sa.Column('id_acudiente', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['puerta_orion_personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id_acudiente'),
    sa.UniqueConstraint('id_persona')
    )
    op.create_table('puerta_orion_cuota',
    sa.Column('id_cuota', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.Column('monto_cuota', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_cuota', sa.Date(), nullable=False),
    sa.Column('descuento', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['puerta_orion_metodo_pago.id_metodo_pago'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['puerta_orion_personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id_cuota')
    )
    op.create_table('puerta_orion_deportista',
    sa.Column('id_deportista', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('estado_deportivo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['puerta_orion_categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['puerta_orion_personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id_deportista'),
    sa.UniqueConstraint('id_persona')
    )
    op.create_table('puerta_orion_usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['puerta_orion_personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('id_persona'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('SesionAuth',
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('token_sesion', sa.String(length=500), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=False),
    sa.Column('ip_origen', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['puerta_orion_usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sesion'),
    sa.UniqueConstraint('token_sesion')
    )
    op.create_table('puerta_orion_deportista_acudiente',
    sa.Column('id_deportista_acudiente', sa.Integer(), nullable=False),
    sa.Column('id_deportista', sa.Integer(), nullable=False),
    sa.Column('id_acudiente', sa.Integer(), nullable=False),
    sa.Column('id_parentesco', sa.Integer(), nullable=False),
    sa.Column('es_responsable', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_acudiente'], ['puerta_orion_acudiente.id_acudiente'], ),
    sa.ForeignKeyConstraint(['id_deportista'], ['puerta_orion_deportista.id_deportista'], ),
    sa.ForeignKeyConstraint(['id_parentesco'], ['puerta_orion_parentesco.id_parentesco'], ),
    sa.PrimaryKeyConstraint('id_deportista_acudiente')
    )
    op.create_table('puerta_orion_rol_usuario',
    sa.Column('id_rol_usuario', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_sesion'], ['puerta_orion_sesiones.id_sesion'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['puerta_orion_usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_rol_usuario')
    )
    op.create_table('puerta_orion_usuario_rol',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['puerta_orion_roles.id_rol'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['puerta_orion_usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puerta_orion_usuario_rol')
    op.drop_table('puerta_orion_rol_usuario')
    op.drop_table('puerta_orion_deportista_acudiente')
    op.drop_table('SesionAuth')
    op.drop_table('puerta_orion_usuario')
    op.drop_table('puerta_orion_deportista')
    op.drop_table('puerta_orion_cuota')
    op.drop_table('puerta_orion_acudiente')
    op.drop_table('diagnostico_persona')
    op.drop_table('PersonasRol')
    op.drop_table('InformacionDeportiva')
    op.drop_table('puerta_orion_personas')
    op.drop_table('puerta_orion_rol_permiso')
    op.drop_table('puerta_orion_mensualidad')
    op.drop_table('puerta_orion_evento')
    op.drop_table('diagnostico')
    op.drop_table('puerta_orion_tipo_evento')
    op.drop_table('puerta_orion_tipo_documento')
    op.drop_table('puerta_orion_sexo')
    op.drop_table('puerta_orion_sesiones')
    op.drop_table('puerta_orion_roles')
    op.drop_table('puerta_orion_permisos')
    op.drop_table('puerta_orion_parentesco')
    op.drop_table('puerta_orion_metodo_pago')
    op.drop_table('puerta_orion_institucion_registro')
    op.drop_table('puerta_orion_grupo_sanguineo')
    op.drop_table('puerta_orion_eps')
    op.drop_table('puerta_orion_ciudad_residencia')
    op.drop_table('puerta_orion_categoria')
    op.drop_table('deporte')
    op.drop_table('TipoEnfermedad')
    op.drop_table('Escuela')
    # ### end Alembic commands ###
