"""eliminar_relacion_diagnostico_deportista

Revision ID: e2bace7221f1
Revises: 932e56d21ca8
Create Date: 2025-10-03 12:52:47.439959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2bace7221f1'
down_revision = '932e56d21ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # No eliminar índices que están siendo usados por claves foráneas
    
    # Eliminar la relación con diagnostico de la tabla puerta_orion_deportista
    with op.batch_alter_table('puerta_orion_deportista', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deportista_diagnostico_nuevo', type_='foreignkey')
        batch_op.drop_column('id_diagnostico_deportista')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recrear la relación con diagnostico
    with op.batch_alter_table('puerta_orion_deportista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_diagnostico_deportista', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_deportista_diagnostico_nuevo', 'diagnostico', ['id_diagnostico_deportista'], ['id_diagnostico'])

    # ### end Alembic commands ###
