"""Actualizar nombres de columnas a estandar

Revision ID: f607fc09752c
Revises: ce296712a0ca
Create Date: 2025-10-18 23:45:17.703042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f607fc09752c'
down_revision = 'ce296712a0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_personas', schema=None) as batch_op:
        batch_op.alter_column('documento',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('correo_electronico',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('direccion',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('puerta_orion_sexo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=150), nullable=False))
        batch_op.drop_column('sexo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_sexo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('nombre')

    with op.batch_alter_table('puerta_orion_personas', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.alter_column('direccion',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('correo_electronico',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('documento',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
