"""add_password_reset

Revision ID: fb54dee06167
Revises: merge_fecha_nacimiento
Create Date: 2025-11-02 15:38:21.330558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb54dee06167'
down_revision = 'merge_fecha_nacimiento'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Nota: Los índices que están vinculados a claves foráneas no se pueden eliminar
    # Solo intentar eliminar si no están vinculados a FK
    
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Intentar eliminar índices solo si no están vinculados a claves foráneas
    try:
        # Verificar si el índice existe y si está vinculado a FK antes de eliminarlo
        fks = inspector.get_foreign_keys('informaciondeportiva')
        fk_columns = [col for fk in fks for col in fk.get('constrained_columns', [])]
        
        # Solo eliminar si id_institucion_registro no está en claves foráneas
        if 'id_institucion_registro' not in fk_columns:
            with op.batch_alter_table('informaciondeportiva', schema=None) as batch_op:
                try:
                    batch_op.drop_index('ix_informacion_deportiva_institucion')
                except Exception:
                    pass  # El índice puede no existir o estar vinculado a FK
    except Exception:
        pass  # Si hay error, continuar
    
    try:
        # Verificar para abonos_mensualidad
        fks = inspector.get_foreign_keys('puerta_orion_abonos_mensualidad')
        fk_columns = [col for fk in fks for col in fk.get('constrained_columns', [])]
        
        if 'id_mensualidad' not in fk_columns:
            with op.batch_alter_table('puerta_orion_abonos_mensualidad', schema=None) as batch_op:
                try:
                    batch_op.drop_index('ix_abono_mensualidad_mensualidad')
                except Exception:
                    pass
    except Exception:
        pass
    
    # NO cambiar fecha_nacimiento aquí - eso se hace en merge_heads_and_fecha_nacimiento.py
    # Esta migración NO debe intentar cambiar fecha_nacimiento porque ya se cambió en la migración anterior
    print("Nota: El cambio de fecha_nacimiento se maneja en la migración merge_heads_and_fecha_nacimiento")
    
    # Eliminar índices de deportista solo si no están vinculados a FK
    try:
        fks = inspector.get_foreign_keys('puerta_orion_deportista')
        fk_columns = [col for fk in fks for col in fk.get('constrained_columns', [])]
        
        with op.batch_alter_table('puerta_orion_deportista', schema=None) as batch_op:
            if 'id_ciudad_recidencia' not in fk_columns:
                try:
                    batch_op.drop_index('ix_deportista_ciudad')
                except Exception:
                    pass
            
            if 'id_eps' not in fk_columns:
                try:
                    batch_op.drop_index('ix_deportista_eps')
                except Exception:
                    pass
            
            if 'id_tipo_sanguineo' not in fk_columns:
                try:
                    batch_op.drop_index('ix_deportista_tipo_sanguineo')
                except Exception:
                    pass
    except Exception:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_deportista', schema=None) as batch_op:
        batch_op.create_index('ix_deportista_tipo_sanguineo', ['id_tipo_sanguineo'], unique=False)
        batch_op.create_index('ix_deportista_eps', ['id_eps'], unique=False)
        batch_op.create_index('ix_deportista_ciudad', ['id_ciudad_recidencia'], unique=False)
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.Date(),
               type_=mysql.SMALLINT(),
               existing_nullable=True)

    with op.batch_alter_table('puerta_orion_abonos_mensualidad', schema=None) as batch_op:
        batch_op.create_index('ix_abono_mensualidad_mensualidad', ['id_mensualidad'], unique=False)

    with op.batch_alter_table('informaciondeportiva', schema=None) as batch_op:
        batch_op.create_index('ix_informacion_deportiva_institucion', ['id_institucion_registro'], unique=False)

    # ### end Alembic commands ###
