"""add_password_reset

Revision ID: fb54dee06167
Revises: 607d95db0456
Create Date: 2025-11-02 15:38:21.330558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb54dee06167'
down_revision = '607d95db0456'  # Cambiado de 'merge_fecha_nacimiento' (no existe) a la última migración válida
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Nota: Los índices que están vinculados a claves foráneas no se pueden eliminar
    # Solo intentar eliminar si no están vinculados a FK
    
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Intentar eliminar índices solo si no están vinculados a claves foráneas
    fks = inspector.get_foreign_keys('informaciondeportiva')
    fk_columns = [col for fk in fks for col in fk.get('constrained_columns', [])]
    
    # Solo eliminar si id_institucion_registro no está en claves foráneas
    if 'id_institucion_registro' not in fk_columns:
        with op.batch_alter_table('informaciondeportiva', schema=None) as batch_op:
            batch_op.drop_index('ix_informacion_deportiva_institucion')
    
    # Verificar para abonos_mensualidad
    fks = inspector.get_foreign_keys('puerta_orion_abonos_mensualidad')
    fk_columns = [col for fk in fks for col in fk.get('constrained_columns', [])]
    
    if 'id_mensualidad' not in fk_columns:
        with op.batch_alter_table('puerta_orion_abonos_mensualidad', schema=None) as batch_op:
            batch_op.drop_index('ix_abono_mensualidad_mensualidad')
    
    # Eliminar índices de deportista solo si no están vinculados a FK
    fks = inspector.get_foreign_keys('puerta_orion_deportista')
    fk_columns = [col for fk in fks for col in fk.get('constrained_columns', [])]
    
    with op.batch_alter_table('puerta_orion_deportista', schema=None) as batch_op:
        if 'id_ciudad_recidencia' not in fk_columns:
            batch_op.drop_index('ix_deportista_ciudad')
        
        if 'id_eps' not in fk_columns:
            batch_op.drop_index('ix_deportista_eps')
        
        if 'id_tipo_sanguineo' not in fk_columns:
            batch_op.drop_index('ix_deportista_tipo_sanguineo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puerta_orion_deportista', schema=None) as batch_op:
        batch_op.create_index('ix_deportista_tipo_sanguineo', ['id_tipo_sanguineo'], unique=False)
        batch_op.create_index('ix_deportista_eps', ['id_eps'], unique=False)
        batch_op.create_index('ix_deportista_ciudad', ['id_ciudad_recidencia'], unique=False)
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.Date(),
               type_=mysql.SMALLINT(),
               existing_nullable=True)

    with op.batch_alter_table('puerta_orion_abonos_mensualidad', schema=None) as batch_op:
        batch_op.create_index('ix_abono_mensualidad_mensualidad', ['id_mensualidad'], unique=False)

    with op.batch_alter_table('informaciondeportiva', schema=None) as batch_op:
        batch_op.create_index('ix_informacion_deportiva_institucion', ['id_institucion_registro'], unique=False)

    # ### end Alembic commands ###
