"""Agregar tabla TransaccionMercadoPago

Revision ID: transaccion_mp
Revises: 9a3e509d98c3
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'transaccion_mp'
down_revision = '9a3e509d98c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puerta_orion_transaccion_mercadopago',
    sa.Column('id_transaccion', sa.Integer(), nullable=False),
    sa.Column('id_pago_mercadopago', sa.String(length=255), nullable=False),
    sa.Column('preference_id', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.Column('datos_pago', mysql.JSON(), nullable=True),
    sa.Column('id_cuota', sa.Integer(), nullable=True),
    sa.Column('id_mensualidad', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cuota'], ['puerta_orion_cuota.id_cuota'], ),
    sa.ForeignKeyConstraint(['id_mensualidad'], ['puerta_orion_mensualidad.id_mensualidad'], ),
    sa.PrimaryKeyConstraint('id_transaccion'),
    sa.UniqueConstraint('id_pago_mercadopago')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puerta_orion_transaccion_mercadopago')
    # ### end Alembic commands ###