"""Agregar tabla TransaccionMercadoPago

Revision ID: transaccion_mp
Revises: 9a3e509d98c3
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from ._helpers_transaccion_mp import create_transaccion_mercadopago_table, drop_transaccion_mercadopago_table

# revision identifiers, used by Alembic.
revision = 'transaccion_mp'
down_revision = '9a3e509d98c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    create_transaccion_mercadopago_table(created_at_nullable=True, updated_at_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    drop_transaccion_mercadopago_table()
    # ### end Alembic commands ###